Repository jenkinsci/oidc-provider-plugin, pull requests merged in 2024-07, with the labels that each got.

#46 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#48 Add a concrete example of a AWS IAM trust policy
  README.md
Labels: documentation

#47 MANAGE permission is enough to validate issuer defined in Jenkins root
  pom.xml
  src/main/java/io/jenkins/plugins/oidc_provider/RootIssuer.java
Labels: enhancement
